# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: AISBERG über DataHandwerk

# # Short description of your site
# # gibt es im aktuellen Template nicht mehr, funktioniert es noch?
# description: Meine Erfahrungen mit dem AnalyticsCreator zur DWH-Automatisierung (ELT, DWH, SSAS)

# Your name to show in the footer
author: Germo Görtz

# --- List of links in the navigation bar --- #

navbar-links:
  Über mich (Profil de): "goertz_profile_de"
    # - Profil (de): "goertz_profile_de"
    # - Profil (de) test: "Germo_Goertz_IT_profile"
    # - Projekthistorie: "goertz_project_history_de"
    # - Referenzen / Bewertungen: "goertz_references"
  Tag Index: "tags"
  DataHandwerk:
    - Dokumentation: "https://datahandwerk.gitlab.io"
    - GitLab Projekt: "https://gitlab.com/datahandwerk/DataHandwerk-toolkit-mssql"
    - Community on Zulip: "https://datahandwerk.zulipchat.com/"
    # - Discussions: "https://github.com/DataHandwerk/DataHandwerk-toolkit-mssql/discussions"
    # - Azure Boards: "https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/_boards/board/t/f3077374-71b6-4a5b-bfd6-24a792bbc352/Microsoft.RequirementCategory/"
  AnalyticsCreator:
    - WebPage: "https://www.analyticscreator.com/"
    - Forum: "https://forum.analyticscreator.com/"
    - WIKI: "https://dev.azure.com/AnalyticsCreator/AnalyticsCreator/_wiki/wikis/AnalyticsCreator.wiki"
    - Community Project: "https://dev.azure.com/AnalyticsCreator/AnalyticsCreator"
    - YouTube: "https://www.youtube.com/channel/UC95xNZUE2e7Wr8n3IluXgrQ"
    # - (Github - old) AnalyticsCreator Toolkit: "https://github.com/aisbergde/AnalyticsCreator_Toolkit"
  Impressum: "impressum"
#  AISBERG: "https://www.aisberg.de"
# nav-search: "search"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/AisbergLogo.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
# Funktioniert nicht, vielleicht mit ""
# svg funktioniert, ist aber zu klein
# title-img: "/assets/img/AisbergLogo.svg"


# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "web@aisberg.de"
  facebook: germo.goertz
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: aisbergde
#  twitter: GermoGortz
#  patreon:
#  medium: yourname
#  reddit: yourname
  linkedin: germo-görtz
  xing: Germo_Goertz
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: germogoertz
  youtube: user/GermoGoertz
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
  telegram: germo_goertz
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

# If you want to show a link to an RSS in the footer, add the site description here.
# If you don't want to show an RSS link, remove the following line.
# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: Aisberg über DataHandwerk

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "aisberg.de"

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 100

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#FFFFFF"
navbar-text-col: "#1e4586"
# unklar, was das ist:
navbar-border-col: "#8fadd1"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#1e4586"
hover-col: "#d62b34"
footer-col: "#FFFFFF"
footer-text-col: "#000000"
footer-link-col: "#1e4586"
footer-hover-col: "#d62b34"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-169285367-1"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-169285367-1"

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/

# utterances:
#   repository: aisbergde/aisbergde.github.io # GitHub username/repository eg. "daattali/beautiful-jekyll"
#   issue-term: title   # Mapping between blog posts and GitHub issues
#   theme: github-light # Utterances theme
#   label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, uncomment the following section. You may leave the reCaptcha
# section commented if you aren't using reCaptcha for spam protection. 
# Using Staticman requires advanced knowledge, please consult 
# https://github.com/eduardoboucas/staticman/ and https://staticman.net/ for further 
# instructions. For any support with staticman please direct questions to staticman and 
# not to BeautifulJekyll.
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well) 
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# To use giscus comments:
# (0) Uncomment the following giscus section, (1) Enable Discussions in your GitHub repository, 
# (2) Install the giscus app in your repository (details at https://giscus.app),
# (3) Fill in *all* the parameters below 
# See more details about giscus and each of the following parameters at https://giscus.app

# <script src="https://giscus.app/client.js"
#         data-repo="aisbergde/aisbergde.github.io"
#         data-repo-id="MDEwOlJlcG9zaXRvcnkyNzE2MzU3NzY="
#         data-category="General"
#         data-category-id="DIC_kwDOEDDVQM4B_lar"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="bottom"
#         data-theme="light"
#         data-lang="de"
#         crossorigin="anonymous"
#         async>
# </script>


giscus:
  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
  repository: "aisbergde/aisbergde.github.io" # GitHub username/repository eg. "daattali/beautiful-jekyll"
  repository-id: "MDEwOlJlcG9zaXRvcnkyNzE2MzU3NzY=" # ID of your repository, retrieve this info from https://giscus.app
  category: "General" # Category name of your GitHub Discussion posts
  category-id: "DIC_kwDOEDDVQM4B_lar" # ID of your category, retrieve this info from https://giscus.app
  mapping: "pathname"
  reactions-enabled: 1
  emit-metadata: 0
  theme: "light"
  lang: "de"

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%-d %B %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts, funktioniert aktuell nicht korrekt
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
      show-avatar: true
      language: de

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - asciidoctor-diagram
  - jekyll-asciidoc
  - jekyll-paginate
  - jekyll-sitemap

# wird insbesondere für asciidoctor-diagram benötigt:

# keep_files:
# - assets/img

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
    # Folgende Ergänzungen für Diagramme
    imagesdir: /assets/img/
    imagesoutdir: assets/img
    # imagesdir: /images
    # # folgendes ist der Standard für "normale" Inhalte,
    # # wird auf jeder Seite definiert
    # # und für lokale Arbeit dort auch je nach env modifiziert
    # imagesdir: /assets/img

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

# funktioniert hier nicht
# muss auf jede Seite einzeln rauf
# head-extra: head_extra.html
