= Referenzen / Bewertungen
:tags: ["Referenzen", "Bewertungen"]

== Würth Logistics AG

//Business Analyst ( Matthias Gerber )

[quote, Business Analyst (Matthias Gerber),]
____
Herr Görtz ist ein höchst profesionller Consulter. Herr Görtz hat während den ersten zwei Wochen vom Aufbau unserem DWH hervorragende Arbeit im initialen Setting und bei der Schulung der Mitarbeiter im Analytics Creator inkl. SSIS / SSAS geleistet. Nach den zwei Wochen sind wir in der Lage, einen grossteil der DWH Struktur und Logiken eigenständig zu pflegen und warten.
____

== Öffentlich-rechtliche Versicherung

//Projektleiter

[quote, Projektleiter]
____
Herr Görtz hat uns in unserem Projekt mehr als 1 Jahr als Haupt-Entwickler unterstützt. Dabei war er zuständig für die Programmierung von Partner- und Vertragsdaten im neu aufgebauten DWH. Herr Görtz hat die Programmierung mit hoher Eigenmotivation und zügig durchgeführt. Daneben war sehr positiv, dass er einen sehr regelmäßigen, konstruktiven und intensiven Austausch mit den Fachkonzeptionierern gehaltet hat und somit stets Dinge hinterfragt und für die Programmierung verbessert hat.
____

== DRK Kliniken Berlin

[quote, Abteilungsleiter Controlling]
____
In der Zusammenarbeit mit dem Berater profitieren wir zum einen von seinem fundierten Geschäftswissen aus dem Bereich der stationären & ambulanten Patientenversorgung, und zum anderen von seiner sehr eigenständigen, zielgerichteten Arbeitsweise, welche den Abstimmungsbedarf deutlich reduziert. Wir sind dabei, mit ihm ein `'wirklich'` integriertes Datenmodell im Krankenhaus umzusetzen, Projektschritte wie Materialwirtschafts-, Belegungs-, OP- und DRG-Informationssystem sind schon erfolgreich abgeschlossen. [...] Auch die Zusammenarbeit zwischen uns, dem Berater und einer weiteren externen beratenden Firma lief und läuft reibungslos. Der Berater hat sich auf professionelle Art sehr gut ins Team integriert, so dass er -- wie gewünscht -- für alle Mitarbeiter ein Ansprechpartner ist , ohne dass durch die Pflege von Sozialkontakten zu viel Projektzeit verloren geht.
____

http://www.drk-kliniken-berlin.de

== Vivantes - Krankenhauskonzern (1)

//Abteilungsleiterin Prozessmanagement

Projekt Behandlungspfadcontrolling und Controlling Hämotherapie, 01/07 - 07/07

//Referenz durch Abteilungsleiterin Prozessmanagement, Vivantes, vom 14.02.08

[quote, Abteilungsleiterin Prozessmanagement, Vivantes - vom 14.02.08]
____
Die Zusammenarbeit mit dem Consultant war hervorragend, insbesondere die Fähigkeit, ganz exakt Ziele des Projektes zu verstehen und für den Kunden umzusetzen, dabei Verständnis und Geduld zu besitzen, dass in der Entwicklung auf der Kundenseite neue Ideen und Aspekte immer wieder entstehen, die zu Erweiterungen und Änderungenswünschen führen. Das sehr große Engagement in der Sache, die Bereitschaft auch unter Zeitdruck für das Projekt zu arbeiten und die sehr sympathische Art, Dinge und Computeranwendungen 'auch relativen Laien' zu erklären, ist großartig. Darüber hinaus schätze ich an dem Consultant, dass er die Kunden 'selbstlos', also auch gegen den eigenen Vorteil, berät. Von Beratern, die vorrangig nur ihre Leistung verkaufen wollen, unterscheidet sich der Consultant durch die Charaktereigenschaft, nur Dinge anzubieten, die aus seiner Sicht auch wirklich für den Kunden nutzbringend sind. Ich kann nur Gutes von der Zusammenarbeit in den Projekten mit dem Consultant berichten und hoffe, dass sich auch in Zukunft Gelegenheit dafür bietet.
____

https://www.vivantes.de/

== Vivantes - Krankenhauskonzern (2)

[quote, Verantwortlicher für zentrales Berichtswesen]
____
Die vom Berater erstellten und betreuten MS SQL-Server- und OLAP-Datenbanken sind Grundlage des zentralen Berichtswesens. Mehrere Datenbankanwendungen werden von vielen zentralen und dezentralen Unternehmensbereichen wie z.B. Controlling, strategische Unternehmensentwicklung, sowie im Qualitäts- und Prozessmanagement regelmäßig genutzt. Die Projekte wurden von der Spezifikation über die Entwicklungs- und Testphase bis hin zur Inbetriebnahme begleitet. Auch Anwenderschulungen wurden vom Berater auf Kundenwunsch durchgeführt. Die bestehenden Anwendungen werden betreut und entsprechend unseren Anforderungen weiterentwickelt. Auch sehr komplexe Anforderungen werden zuverlässig, schnell, kompetent, mit großer Einsatzbereitschaft zu unserer vollsten Zufriedenheit umgesetzt. Dabei trägt der Berater mit eigenen Ideen und vielen Erfahrungen aus anderen Projekten wesentlich dazu bei, den Nutzen unserer Datenbankanwendungen zu optimieren und zu maximieren. Die Kommunikation und Zusammenarbeit mit uns Fachanwendern klappt hervorragend. Wir blicken inzwischen auf eine fünfjährige, erfolgreiche Zusammenarbeit zurück, die wir sehr gerne in der Zukunft fortsetzen möchten, und können den Berater auf jeden Fall weiterempfehlen.
____

https://www.vivantes.de/

== Bezirkskliniken Mittelfranken

[quote, Verantwortlicher für zentrales Berichtswesen]
____
Der Berater hat im Bereich Personal und Rechnungswesen anspruchsvolle IT-Lösungen sowie hochkomplexe OLAP-Datenbanken mit Belegungs- und Falldaten für unser unternehmensweites Reporting entwickelt und aufgebaut. Er verfügt über umfassende Fachkenntnisse im Krankenhausbereich und konnte deshalb alle Anforderungen stets zu unserer vollsten Zufriedenheit umsetzen. Ihn zeichnen besonders seine Zuverlässigkeit, seine große Einsatzbereitschaft, Engagement und Termintreue aus. Wir blicken auf eine gute Zusammenarbeit seit nun fast vier Jahren zurück, die wir auch gerne zukünftig fortsetzen möchten.
____

http://www.bezirkskliniken-mfr.de/

== GfS Gesellschaft für Standortsicherung Unternehmensberatung mbH

//Geschäftsführer

Projekt Krankenhauscontrolling mit MS SQL Analysis Services, 10/05 - 02/08

//Referenz durch Geschäftsführer, Unternehmensberatung (10 MA), vom 18.02.08
[quote, Geschäftsführer, Unternehmensberatung (10 MA) - vom 18.02.08]
____
Der Consultant entwickelt für uns seit mehr als 2 Jahren OLAP-Datenbanken für Controllinganwendungen im Krankenhausbereich. Ich schätze an ihm seine absolute Zuverlässigkeit, seine Termintreue, sein hohes Engagement und seine Kreativität. Wir werden mit ihm auch zukünftig gerne zusammenarbeiten.
____

http://www.gesundheitsconsult.de/

== Opel



[quote, BI Manager (Pete Sansom)]
____
I recently worked with Germo on a BI project to analyse customer behaviour. I found Germo's technical skills on the Microsoft stack to be very high and him to be generally very experienced in data modeling and BI. Germo is a diligent and responsible professional.

He is determined to do a good job and offers good value for his customers. I would recommend Germo and would not hesitate to work with him in the future.
____

== Henkel AG & Co. KGaA



[quote, IT Projektleiter]
____
Auch sehr komplexe Anforderungen werden zuverlässig, schnell, kompetent, mit großer Einsatzbereitschaft zu unserer vollsten Zufriedenheit umgesetzt. Die Kommunikation und Zusammenarbeit mit den Fachanwendern wie auch mit den IT Kollegen klappt hervorragend. Aufgrund seines zielgerichteten von großer Sorgfalt, Systematik, Selbstständigkeit und Verantwortungsbewußtsein geprägten Arbeitsstils gelang es ihm, komplexe Lösungen stets erfolgreich umzusetzen. Er bewieß zudem, dass er flexibel auf neue Anforunden eingehen kann um diese innovativ zu lösen und umzusetzen. Wir haben den Mitarbeiter als einen außerordentlich belastbaren und ausdauernden Mitarbeiter kennen gelernt, der seinen Tätigkeiten mit Fleiß und Zielstrebigkeit durchgeführt hat. Wir können den Berater auf jeden Fall und uneingeschränkt weiterempfehlen.
____

http://www.henkel.de

== Investitionsgüterhersteller (>20.000 MA)



[quote, Projektmanager]
____
Der Berater besitzt sehr gute Kenntnisse im Aufbau und Betrieb von komplexen Data Warehouse Systemen und rund um die Themen BI-Solutions. Mit seinem umfassenden fachlichen Know-How und Erfahrungen konnte er die anspruchsvollen Anforderungen innovativ und zur unserer vollsten Zufriedenheit umsetzen. Die Zusammenarbeit und Kommunikation klappt hervorragend. Neben seinem tiefgehenden Fachwissen sind vor allem seine hohe Einsatzbereitschaft, Engagement und Anpassungsfähigkeit sowie seine sorgfältige, innovative und selbständige Arbeitsweise hervorzuheben. Wir bedanken uns für die erfolgreiche Zusammenarbeit und werden mit ihm auch in der Zukunft gerne zusammenarbeiten.
____

== Kelvion Holding GmbH



[quote, Teamlead Business Intelligence]
____
Der Consultant war im Rahmen eines größeren Projektes zur Einführung eines Datawarehouses in unserem Unternehmen für die Architektur und Programmierung mehrer Analysis-Services-Cubes auf Basis von SQl-Server 2016 verantwortlich. Er überzeugte durch ein hohes Maß an fachlichem und technischen Wissen und legte bei der Konzeptionierung der Lösung großen Wert auf Transparenz und Flexibilität. Wir sind mit seiner Arbeit äußerst zufrieden und empfehlen ihn uneingeschränkt weiter!
____

https://de.kelvion.com/

== Volkswagen Nutzfahrzeuge



[quote, Auftraggeber, Fachbereich Restwertmanagement VWN]
____
Der Consultant war bei uns mit der (Weiter-)entwicklung des mathematisch- / statistischen Teils unseres Projektes betraut, insbesondere mit dem Aufbau komplexer Prognosemodelle, unter anderem mit Künstlichen Neuronalen Netzen (KNN), multipler Regression und weiteren statistischen Verfahren (BI im Microsoft-Umfeld + Statistica und Tableau). Aus den Outputdaten des KNN und zahlreichen weiteren Datenquellen konzipierte und entwickelte der Consultant nach Kundenvorgabe eigenständig Visualisierungen in Tableau (Standardberichte für Fachbereiche, Dashboards, Decision Support). Der Consultant verfügt über ein beeindruckendes Auffassungsvermögen; vor dem Hintergrund der hohen Komplexität des bestehenden Systems und des sehr spezifischen Fachgebietes arbeitete er sich extrem schnell in die bestehenden Workflows, Prozesse und auch in das für ihn völlig neue Fachgebiet ein. Nach kürzester Zeit entdeckte (und behob) er bestehende Fehler und hatte stets einen Lösungsvorschlag auch für neue, komplexe Problemstellungen parat. Neben seinem hohen analytischen Denkvermögen zeichnet ihn besonders seine Fähigkeit zum 'Querdenken' aus, was im Team dazu anregt, den Status Quo zu überdenken, bestehende Strukturen aufzubrechen und gegebenenfalls neue (Lösungs-)Wege zu beschreiten. Ich danke dem Consultant für die gute und bereichernde Zusammenarbeit und wünsche ihm für seinen weiteren privaten und beruflichen Lebensweg viel Erfolg und alles Gute.
____

http://www.volkswagen-nutzfahrzeuge.de

== Nestlé



[quote, Project Manager Dynamic Forecast]
____
The consultant has been an asset to our project. He is hard working and has a strong sense of Customer Service. He is able to break down complex requirements into logical tasks and has frequently demonstrated his ability to come up with innovative solutions to some of the challenges that we have faced. I would consider him to be an expert in his area.
____

http://www.nestle.com/

== Landwirtschaftliche Rentenbank

//Leiter Anwendungsentwicklung OLAP, DWH, Java

[quote, Leiter Anwendungsentwicklung OLAP DWH Java]
____
Der Berater besitzt sehr gute Kenntnisse bei der Entwicklung und im Design von IT-Anwendungssystemen. Darüber hinaus sind seine sehr guten Kenntnisse in der Modellierung von anspruchsvollen OLAP-Lösungen hervorzuheben. Der Berater hat durch seine Arbeitweise, die durch Selbstständigkeit, Einsatzbereitschaft und Zielorientierung gekennzeichnet ist, durch kreative Lösungsansätze und den aktiven Austausch von Know-How mit anderen Teammitgliedern maßgeblich zu den Erfolgen in den Projekten beigetragen. Die ihm übertragenen Aufgaben führte er zu unserer vollsten Zufriedenheit aus. Unsere Fachanwender loben die schnelle und kompetente Umsetzung ihrer Anforderungen sowie die erhaltene praktische Hilfe bei der Verwendung der analytischen Anwendungen. Sein Verhalten war stets einwandfrei und kooperativ. Wir bedanken uns für die gute Mitarbeit beim Berater und hoffen auf eine weitere unternehmerische Zusammenarbeit.
____

https://www.rentenbank.de/

== MIS AG

//Geschäftsführer
//
//Projekt Consultant für Business Intelligence, 09/99 - 09/04
//
//Referenz durch Geschäftsführer, BI-Software u. -Beratung (460 MA), vom 28.06.04

Projekt im Rahmen einer Festanstellung durchgeführt

[quote, Geschäftsführer, BI-Software u. -Beratung (460 MA) - vom 28.06.04]
____
`[...]` Als technischer Projektleiter arbeitete sich der Mitarbeiter zielorientiert mit viel Engagement und Eigeninitiative in komplexe Arbeitsgebiete ein und bewältigte neue Arbeitssituationen stets gut und sicher. Er verfügte über umfassende und vielseitige Fachkenntnisse, die er stets ktualisierte und erweiterte. In bereichsübergreifenden Zusammenhängen setzte er die richtigen Prioritäten und überzeugte mit guten Lösungsvorschlägen. Aufgrund seines zielgerichteten von großer Sorgfalt, Systematik, Selbstständigkeit und Verantwortungsbewußtsein geprägten Arbeitsstils gelang es ihm, komplexe Lösungen stets erfolgreich umzusetzen. Auf Grund seiner umfassenden Kenntnisse im Krankenhaus- und Verlagsbereich war der Mitarbeiter federführend an der Entwicklung der '`[...]` Business Solution Krankenhäuser', der 'DRC's (Diagnosis Related Costs)', der '§21-DRG-Analyse' für Krankenhäuser und der '`[...]` Business Solution - Anzeigeninformationssystem für Verlage' beteiligt. Der Mitarbeiter konzipierte und implementierte verschiedene kundenspezifische Lösungen für das Medizin- und Krankenhauscontrolling und das Verlagswesen. Wir bescheinigen dem Mitarbeiter, dass er über ausgeprägte analytische Fähigkeiten und eine starke IT-Ausrichtung verfügt, die er erfolgreich in seine Arbeit integriert. Der Mitarbeiter nahm im Rahmen seiner Tätigkeit an den Schulungen der `[...]` Academy teil und erwarb sich hier umfangreiches, qualifiziertes Wissen in Projektmanagement und Teamführung. Immer wieder verstand er es, in seinem Arbeitsgebiet wichtige Impulse zu geben und neue Wege zu beschreiten. Seine Innovationsbereitschaft, sein Verantwortungsbewusstsein, seine Kompetenz und seine Zuverlässigkeit waren ein wichtiger Beitrag für unser Unternehmen und ein Indikator für Wachstum und Erfolg. Der Mitarbeiter erfüllte die ihm obliegenden Aufgaben stets zu unserer vollsten Zufriedenheit. Das Verhalten des Mitarbeites gegenüber der Unternehmensleitung und seinen Kollegen waren gleichermaßen vorbildlich. Gleiches gilt für seinen von Aktivität und Serviceorientierung geprägten Umgang mit Kunden. Der Mitarbeiter stellte die Unternehmensziele beim Kunden stets erfolgreich in den Vordergrund. Er war ein engagierter und begeisterungsfähiger Mitarbeiter, der wegen seiner kooperativen und hilfsbereiten, sachlichen Art gleichermaßen bei Vorgesetzten, Mitarbeitern und Kunden beliebt war. Wir haben den Mitarbeiter als einen außerordentlich belastbaren und ausdauernden Mitarbeiter kennen gelernt, der seinen Tätigkeiten mit Fleiß und unverkennbarer Freude nachgeht. `[...]` Wir bedauern sehr, in ihm einen ausgezeichneten Mitarbeiter zu verlieren und danken ihm für die zu jedem Zeitpunkt sehr guten Leistungen und die angenehme Zusammenarbeit. `[...]`
____

http://www.infor.de
