= Projekthistorie
:tags: ["Projekthistorie"]

zeitlich sortiert nach Projekt-Ende

== 03/2023 - bis jetzt; softwareONE

* BI Entwicklung
* Migrationen
** von SSAS OLAP über SSAS Tabular zu Power BI Premium
** von on premise Data Warehouse zu Data Lakehouse

== 09/2019 - bis jetzt; iconcare (BInovis & Visality)

Branche:: Gesundheitswesen, Krankenhaus, Logistik

Größe:: 10-50 Mitarbeiter

=== Microsoft BI Architekt und Entwickler

=== Hospital Process Analyzer

https://iconcare.eu/index.php/hospital-process-analyzer/

30 Jahre Erfahrung aus der Prozesssteuerung von Krankenhäusern und Flughäfen stecken in diesem von iconcare für die Prozesssteuerung entwickelten Werkzeug.

Ziel des Projektes war die Entwicklung eines standardisierten Steuerungswerkzeuges zur Optimierung der OP-Planung und -Steuerung in Krankenhäusern mit bis dahin nicht am Markt verfügbaren Merkmalen – insbesondere zur frühzeitigen Erkennung von und zur rechtzeitigen Reaktion auf sich abzeichnende Prozessstörungen.

Prozess- und Zeitanalysen in Krankenhäusern (beispielsweise OP Zeiten, OP Wechselzeiten, OP Auslastung, Personal Auslastung)

verwendete Technologien:

* Microsoft SQL Server
* Power BI

=== SmartHome

* überwachtes Wohnen in Heimen
* smarte Stromzähler
* Zeitanalysen von Stromverbräuchen
* HomeAssistant
* IoT
* MQTT
* Microsoft SQL Server (on-premise)
* Python

== 05/2022 - 01/2023; Nomura Asset Management Europe KVG mbH

Branche:: Banken und Finanzdienstleistungen

Größe:: 10-50 Mitarbeiter

=== Aufbau neues DWH, Migration aus altem DWH

* DWH und ELT werden mit AnalyticsCreator erstellt
* Microsoft SQL Server (on-premise)
* AnalyticsCreator
* DataHandwerk
* Antora
* git

== 11/2022 - 12/2022; TÜV Rheinland i-sec GmbH

* Coaching Datenmodellierung SSAS und Power BI
* Coaching Microsoft BI und Microsoft SQL Server

== 09/2022 - 12/2022; Kerkhoff Experts GmbH

=== Quick Scan für den Einkauf

* Spend-Cube mit Microsoft Power BI

== 08/2021 - 06/2022; SYSKRON - im House of Krones

Branche:: Industrie und Maschinenbau

Krones ist Weltmarktführer für Abfüllanlagen

Größe:: > 10.000 Mitarbeiter (Krones)

=== Unterstützung im Bereich Microsoft SQL Server / BI

* Microsoft SQL Server (on-premise)
* Power BI
* DataHandwerk
* Antora
* git
* jira

== 01/2022 - 04/2022; Roller

Branche:: Konsumgüter und Handel

Größe:: ?

=== Unterstützung im Bereich Microsoft SQL Server / BI

* Microsoft SQL Server (on-premise)
* Power BI
* BimlExpress
* git

== 03/2022 - 04/2022; Betty Barclay

Branche:: Konsumgüter und Handel

Größe:: 1000 - 5000 Mitarbeiter

=== Unterstützung im Bereich Microsoft SQL Server / BI

* Microsoft SQL Server (on-premise)
* Power BI
* BimlExpress
* git

== 08/2021 - 12/2021; abcfinance

Branche:: Banken und Finanzdienstleistungen

Größe:: 500-1000 Mitarbeiter

=== Konzeption und PoC für eine «Source to target» - Dokumentation für das zentrale DWH über die verschiedenen Schichten (u. a. Data Vault, Starschema und tabulare Modelle)

* umfasst Versionierung der Dokumentation, Anreicherung mit Metadaten und fachlichen Daten, Bereitstellung von Schnittstellen für Fachbereiche zur Administration und Konsumierung, Verknüpfung mit Informationen aus Quellsystemen im Rahmen der ETL/ELT-Prozesse etc.
* Unterstützung bei Umsetzung der Lösung
* Entwicklung entsprechender Prozesse/Workloads für die Erzeugung und Aktualisierung der Dokumentation
* Einführung eines entsprechenden Werkzeugs
* Microsoft SQL Server (on-premise)
* DataHandwerk
* Antora
* git
* TFVC

== 04/2021 - 06/2021; Peter Hahn GmbH

Branche:: Konsumgüter und Handel

Größe:: >1.000 Mitarbeiter

=== Power BI Expert

* Begleitung von Workshops mit Bezug zu BI Anforderungen
* Beratung und Erstellung von Mappings & BI Umsetzungen +
Umsetzen von Anforderungen in technische BI Lösungen
* Zusammenarbeit mit anderen Teilprojekten und Zuarbeit von Ergebnissen
* Microsoft SQL Server (on-premise)
* Power BI
* TFVC

== 02/2020 - 03/2021; MEAG - Munich ERGO Assetmanagement GmbH

Branche:: Banken und Finanzdienstleistungen

Größe:: 500-1000 Mitarbeiter

=== Performancemessung Reporting: Microsoft BI Architekt und Entwickler

* Entwicklung eines Reporting-Tools mittels Power BI, mit dem Ziel der automatisierten Report-Erstellung aus Sim Corp Dimension anstelle des bisherigen Reportings mittels Excel-Sheets.
* DWH, ELT und SSAS werden mit AnalyticsCreator erstellt.
* einzelne Module mit Python, Powershell
* Microsoft SQL Server (on-premise)
* AnalyticsCreator
* Power BI
* git

== 09/2019 -- 03/2020; Swisscom

Branche:: Telekommunikation

Größe:: >10.000 Mitarbeiter

=== Import und Verarbeitung von Daten aus Service Now für ein Reporting, Erstellung DWH mit AnalyticsCreator, Berichte mit Power BI

* Import von Daten aus Service Now über die API (mit Python)
* Import, Integration und Transformation in einem DWH im SQL Server
* Analytische Datenbank mit SSAS
* Berichte im Power BI
* DWH, ELT und SSAS werden mit AnalyticsCreator erstellt
* Microsoft SQL Server (on-premise)
* AnalyticsCreator
* git
* jira

[#project_drkkliniken_2019]
== 11/2010 - 12/2019; DRK Kliniken Berlin

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 1000-5000 Mitarbeiter

=== Krankenhaus DWH: Microsoft BI Architekt und Entwickler

Projektinhalte:

* Materialwirtschafts-
* Belegungs-
* Operations- und
* DRG-Informationssystem
* Bau- und Investitionscontrolling
* OP-Management (Planung, Nutzung, Wechselzeiten, ...),
* monatliches Berichtswesen
* Finanzplanung und Hochrechnungen
* Migration BI Anwendungen von SQL Server 2000 auf SQL Server2008 R2
* Schulung der Anwender

Datenquellen:

* Orbis (KIS = KrankenhausInformationsSystem) u. a.

Kenntnisse:

* Planung, Controlling, Anforderungsanalyse, Konzeption, Kommunikation mit Fachbereich, Performance Optimierung, Berichtswesen, Dokumentation, Test

Produkte:

* Microsoft SQL Server 2008 R2 on-premise (relational, SSAS, SSIS, SSRS)
* Microsoft Access
* Cubeplayer
* Subversion

Aktuell: regelmäßiger Support, um das System "am Laufen zu halten", bis irgendwann die vollständige Migration in ein klinisches DWH des KISAnbieters abgeschlossen sein wird.

Referenz: xref:goertz-references.adoc#referenz_drkkliniken[]

[#project_wuerth_logistics_2019]
== 11/2019 - 12/2019; Würth Logistics AG

Branche:: Transport und Logistik

Größe:: 50-250 Mitarbeiter

=== Erstellung eines DWH mit dem AnalyticsCreator

Verwendung des *AnalyticsCreator* zur Erstellung eines Reporting-DWH für Daten der Logistik im SQL Server + Analytische Datenbank (SSAS Tabular) als Grundlage eines flexiblen Berichtswesens mit PowerBI oder anderen Frontends.

Coaching der internen Entwickler zur selbständigen Weiterentwicklung des DWH mit dem AnalyticsCreator

Datenquelle:

* operatives Logistik-DWH (Oracle), eine Anbindung weiterer Datenquellen ist geplant: SAP u. a.

Das schweizer Logistik-Unternehmen ist zuständig für die weltweite Koordination der Logistik eines deutschen Großkonzerns, des Weltmarktführers für den Vertrieb von Montage- und Befestigungsmaterial.

* Microsoft SQL Server (on-premise)
* AnalyticsCreator
* git

Referenz: xref:goertz-references.adoc#referenz_wuerth_logistics[]


[#project_provinzial_2019]
== 10/2018 - 09/2019; Provinzial Nord-West

Branche:: Versicherungen

Größe:: 5000-10.000 Mitarbeiter

=== Aufbau neues DWH: Microsoft BI Architekt und Entwickler, Microsoft BI-Analyse-Plattform, Analyticscreator

Aufbau eines neuen DWH, gehostet auf Microsoft Azure, basierend auf Microsoft SQL BI Technologien

* Microsoft SQL Server (relational, SSAS, SSIS) on-premise und Azure Cloud
* Power BI
* AnalyticsCreator
* Big Data
* jira
* git

Referenz: xref:goertz-references.adoc#referenz_provinzial[]

== 08/2018 - 10/2018; ZEISS Group

Branche:: Industrie und Maschinenbau

Größe:: >10.000 Mitarbeiter

=== Durchlaufzeiten von Produktionsschritten: Microsoft BI Architekt und Entwickler, Microsoft BI-Analyse-Plattform, Analyticscreator

* Durchlaufzeiten von Produktionsschritten
* Re-Design einer bestehenden Power BI Lösung: Konvertierung in DWH + SSAS Tabular zwecks Performance-Optimierung und Verbesserung der Auswertungsmöglichkeiten.
* Kombination von Logik im DWH (Microsoft SQL Server) und in SSAS Tabular
* DWH, ELT und SSAS werden mit AnalyticsCreator erstellt.
* Microsoft SQL Server (on-premise)
* AnalyticsCreator
* Power BI
* TFVC
* git

=== Microsoft Azure - Unterstützung bei Verwendung von Azure Diensten, Migration von SSAS Lösungen zu Azure, ETL / ELT, diverses

* SQL Server (on-premise und Azure Cloud)

[#project_zeiss_2018]
== 03/2016 - 09/2018; ZEISS Group

Branche:: Industrie und Maschinenbau

Größe:: >10.000 Mitarbeiter

* Microsoft SQL Server (on-premise)

=== BICC (BI Competence Center) - Dashboards mit Datazen, Microsoft BI-Analyse- Plattform: Microsoft BI Architekt und Entwickler

* ETL, DWH und Berichte: Dashboards für das Projekt-Controlling mit Datazen
* Import von Daten aus SAP und Essbase
* SAP-Anbindung mit cMORE/Connect for SAP (basiert auf Theobald SAP Integration)

Produkte:

* Datazen
* Microsoft SQL Server (on-premise)
* TFVC

Kernprojekt 03.2016 - 04.0216, Danach bis 09.2018 laufender Support bis und einschließlich Migration auf ServiceNow

Referenz: xref:goertz-references.adoc#referenz_zeiss[]

== 11/2017 - 07/2018; Adecco Germany Holding SA & Co. KG

Branche:: Personaldienstleiter

Größe:: >10.000 Mitarbeiter

=== "Candidate-Cube": Microsoft BI Architekt und Entwickler, Microsoft BI-Analyse-Plattform, Analyticscreator

Das bestehende Datawarehouse soll um ein "Candidate-Cube" erweitert werden:

* Aufnahme von fachlichen Anforderungen
* Spezifikationserstellung
* technische Umsetzung
* Erstellung der ETL-Prozesse (SSIS)
* Cube Erstellung (SSAS)
* Reporterstellung (SSRS)
* DWH, ELT und SSAS werden mit AnalyticsCreator erstellt.
* Vorbereitung einer möglichen Migration in Azure

Produkte:

* Microsoft SQL Server (relational, SSAS, SSIS) on-premise
* Power BI
* AnalyticsCreator
* TFVC

[#project_opel_2017]
== 05/2017 - 11/2017; Adam Opel GmbH

Branche:: Automobil und Fahrzeugbau

Größe:: >10.000 Mitarbeiter

=== Churn-Prevention: Microsoft BI Architekt und Entwickler, Microsoft BI-Analyse-Plattform, Analyticscreator, Data Scientist

* Vorhersage von Churn-Quoten (Wechsel zu anderen Herstellern), Auswertungen
* Data Vault, Data Mining, Prediction
* Microsoft SQL Server (relational, SSAS, SSIS) on-premise
* Power BI
* AnalyticsCreator
* DWH, ELT und SSAS werden mit AnalyticsCreator erstellt
* TFVC oder git

Referenz: xref:goertz-references.adoc#referenz_opel[]

[#project_kelvion_2017]
== 07/2016 - 06/2017; Kelvion

Branche:: Industrie und Maschinenbau

Größe:: 1000-5000 Mitarbeiter

=== SSAS Datenbanken für Planungssystem im Zusammenhang mit Tagetik: Microsoft BI Architekt und Entwickler, Microsoft BI-Analyse-Plattform

* Microsoft SQL Server 2016 (relational, SSAS, SSIS, SSRS) on-premise
* cMORE/Connect for SAP (basiert auf Theobald SAP Integration)
* cMORE/XL (XLCubed)
* Targit
* Power BI
* git

Referenz: xref:goertz-references.adoc#referenz_kelvion[]

== 04/2017 - 05/2017; Kuhn und Bülow Versicherungsmakler Group

Branche:: Versicherungen

Größe:: 10-50 Mitarbeiter

=== Berichtswesen und Statistiken mit Power BI

Grundlagen für Statistiken und Berichte erstellen, um basierend auf Daten des operativen Systems Auswertungen nach Versicherungsnehmern, Versicherern, Schäden und Prämien zu ermöglichen.

* Power BI
* TFVC

== 09/2016 - 12/2016; airberlin

Branche:: Transport und Logistik

Größe:: 5000-10.000 Mitarbeiter

=== Customer Segmentation, Ancillaries: Microsoft BI Architekt und Entwickler

* Microsoft SQL Server 2014 (relational, SSAS, SSIS) on-premise
* jira
* TFVC

== 06/2016 - 07/2016; proXcel GmbH

Branche:: Beratung

Größe:: 10-50 Mitarbeiter

=== Unterstützung bei Analyse, Bearbeitung und Auswertung komplexer Datenpakete eines Produktionsprozesses mit Microsoft-BI-Analyse-Plattform, Data Mining

== 05/2016 - 05/2016; Heraeus Kulzer

Branche:: Industrie und Maschinenbau

Größe:: 1000-5000 Mitarbeiter

=== BI Support, Microsoft BI-Analyse-Plattform

* Microsoft SQL Server (relational, SSAS, SSIS) on-premise
* TFVC

[#project_vgsg_2016]
== 06/2015 - 03/2016; Volkswagen Gebrauchtfahrzeughandels und Service GmbH (VGSG)

Branche:: Automobil und Fahrzeugbau

Größe:: >10.000 Mitarbeiter

=== BI Competence Center Volkswagen Nutzfahrzeuge, Datamining, neuronale Netze, Visualisierung, Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler, Data Scientist

DML: Data Mining Leasing, DM VGSG - Data Mining VGSG (junge Gebrauchte)

* Datamining mit Statistica
* neuronale Netze
* Prognose von Marktwerten (Restwertmanagement) und Verkaufsmengen für gebrauchte Volkswagen-Nutzfahrzeuge und Leasingfahrzeuge
* HIS: Händler Informationssystem
* PuRAS: Profitabilitäts- und Rechnungsanalyse After Sales
* Stammdaten-Management
* Visualisierungen mit Tableau
* BI Entwicklung mit Microsoft SQL Server (relational, SSAS, SSIS) on-premise
* Wherescape
* TFVC oder jira

der wissenschaftliche Hintergrund wird hier genauer erklärt: +
https://www.wi2017.ch/images/wi2017-0173.pdf +
Gleue, C.; Eilers, D.; von Mettenheim, H.-J.; Breitner, M. H. (2017): +
Decision Support for the Automotive Industry: Forecasting Residual Values using Artificial Neural Networks, +
in Leimeister, J.M.; Brenner, W. (Hrsg.): Proceedings der 13. Internationalen Tagung +
Wirtschaftsinformatik (WI 2017), St. Gallen, S. 1205-1219

Referenz: xref:goertz-references.adoc#referenz_vgsg[]

[#project_henkel_2015]
== 08/2012 - 05/2015; Henkel AG & Co. KGaA

Branche:: Konsumgüter und Handel

Größe:: >10.000 Mitarbeiter

=== SCOUT (= Supply Chain Optimization Unified Toolbox), Microsoft BI-Analyse- Plattform: Microsoft BI Architekt und Entwickler

* Inventory
* Order to Cash
* Physical Distribution
* Forecast Accuracy
* Product Availability
* Days of Supply
* Slow Mover Detection for financial devaluation

Migration und vor allem Erweiterung einer Anwendung von SAP BW auf Microsoft SQL Server

BI Design und Entwicklung mit Microsoft SQL Server 2012 on-premise

Hauptfokus: SSAS, Datamart, auch SSIS

* Berichtswesen mit XLCubed
* SAP-Anbindung mit cMORE/Connect for SAP (basiert auf Theobald SAP Integration)
* TFVC

Referenz: xref:goertz-references.adoc#referenz_henkel[]

[#project_bkm_2012]
== 10/2005 - 08/2012; Bezirkskliniken Mittelfranken, Ansbach

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 1000-5000 Mitarbeiter

=== Krankenhaus: Konzeption und Realisierung analytischer Anwendungen für das Controlling und Personalwesen, Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

Psychiatrische Krankenhäuser, Ressort Controlling, Zentrales Personalwesen

Konzeption und Realisierung analytischer Anwendungen für:

* Finanzcontrolling
* Wirtschaftsplanung
* Personaldatencontrolling
* Belegungscontrolling
* Medizincontrolling der psychiatrischen und somatischen Fälle

laufende Betreuung

Migration Microsoft SQL Server 2000 auf Microsoft SQL Server 2005 bzw. 2008 (on-premise)

Datenquellen:

* Orbis (KrankenhausInformaionsSystem)
* PWS (Personaldaten)
* Excel
* andere

Referenz: xref:goertz-references.adoc#referenz_bkm[]

[#project_nestle_2012]
== 02/2011 - 05/2012; Nestlé Suisse S.A

Branche:: Konsumgüter und Handel

Größe:: >10.000 Mitarbeiter

=== Dynamic Planning Framework - Dynamic Forecast: Microsoft BI Architekt und Entwickler

* BI Konzeption, Design und Entwicklung mit Microsoft SQL Server 2005 bzw. 2008 (ETL, Staging, Datawarehouse)
* Performance Tuning

Anforderungsanalyse, Konzeption, Kommunikation mit Fachbereich, Entwicklung, Dokumentation, Test, Performance Optimierung, Wartung, Beratung

Microsoft SQL Server 2005, Microsoft SQL Server 2008 R2 (on-premise)

Referenz: xref:goertz-references.adoc#referenz_nestle[]

== 10/2011 - 04/2012; MTS (Mobile TeleSystems OJSC), Moskau (Russland)

Branche:: Telekommunikation

Größe:: >10.000 Mitarbeiter

=== Einkaufscontrolling - Procurement Performance Management (PPM), Spend Control, Supplier Consolidation: BI Entwickler

* Procurement Performance Management (PPM)
* Spend Control
* Supplier Consolidation
* Microsoft SQL Server (on-premise) und SSAS

Details: http://www.orpheus-it.com/

[#project_hgc_gfs_2011]
== 10/2005 - 12/2011; HGC GesundheitsConsult GmbH

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 10-50 Mitarbeiter

=== freie Mitarbeit als Experte für Geschäftsanalyse (BI) in Krankenhäusern, Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

Partner: GfS (Gesellschaft für Standortsicherung) \=> HGC GesundheitsConsult GmbH \=> Vendus

Projektinhalte:

* Krankenhauscontrolling
* Medizincontrolling
* Konzeption und Entwicklung von Datenmodellen, Analyseverfahren und Berichtssystemen für folgende Einsatzgebiete:
** Markt- und Wettbewerbscontrolling der medizinischen Leistungen
** Leistungsstrukturvergleiche
** Kennzahlen-Leistungsvergleiche (Benchmark)
** Einweisercontrolling
** Controlling medizinischer Behandlungspfade / Versorgungspfade
** Finanzcontrolling
** Fallbezogene Kostenträgerrechnung mit Fallroherträgen und Deckungsbeiträgen oder als Vollkostenrechnung
** Wirtschaftsplanung
** Personaldatencontrolling
** Belegungscontrolling
** Leistungsvergleiche zwischen Abteilungen und Häusern innerhalb eines Konzerns oder Klinikverbundes

Datenquellen:

* diverse (SAP, ORBIS, Textdateien, Excel, ...)

* Microsoft SQL Server (2000, 2005, 2008) relational, MSAS, SSAS, DTS, SSIS (on-premise)
* Bissantz Deltamaster
* Subversion

Referenz: xref:goertz-references.adoc#referenz_gfs[]

== 11/2010 - 02/2011; otto group

Branche:: Konsumgüter und Handel

Größe:: >10.000 Mitarbeiter

=== P4P CoreDWH - Datamarts/Reports, Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

* Multichannel-Einzelhandel
* Finanzdienstleistungen
* Service

BI Konzeption, Design und Entwicklung mit Microsoft SQL Server

Anforderungsanalyse, Konzeption, Kommunikation mit Fachbereich, Entwicklung, Dokumentation, Test, Performance Optimierung, Wartung, Beratung, Berichtswesen

Microsoft SQL Server 2008 R2 (relational, SSAS, SSIS) (on-premise)

== 09/2010 - 11/2010; Krones AG

Branche:: Industrie und Maschinenbau

Größe:: >10.000 Mitarbeiter

=== Migration Auftragseingangsstatistik von SAP BW auf Microsoft SQL Server: Microsoft BI Architekt und Entwickler

BI Design und Entwicklung mit Microsoft SQL Server

Anforderungsanalyse

* Microsoft SQL Server 2008 R2 (relational, SSAS, SSIS) (on-premise)
* SAP-Anbindung mit cMORE/Connect for SAP (basiert auf Theobald SAP Integration)
* TFVC (?)

== 01/2010 - 08/2010; Henkel AG & Co. KGaA

Branche:: Konsumgüter und Handel

Größe:: >10.000 Mitarbeiter

=== GLOBIS (Global Business Information System), COLOR (Common Local Profitability Reporting), Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

BI Design und Entwicklung mit Microsoft SQL Server

Anforderungsanalyse

Microsoft SQL Server 2008 R2 (relational, SSAS, SSIS) (on-premise)

[#project_vivantes_2010]
== 01/2003 - 04/2010; Vivantes GmbH - Netzwerk für Gesundheit

Branche:: Gesundheitswesen, Krankenhaus

Größe:: >10.000 Mitarbeiter

=== Krankenhaus - zentralen Finanz- und DRG-Berichtswesen, Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

Projektinhalte:

Bereiche

* Controlling
* Kostenträgerrechnung
* Qualitäts- und Prozessmanagement
* ...

Inhalte

* technische Konzeption
* Modellierung und Betreuung des zentralen Finanz-Berichtswesens und des DRG-Berichtswesens
* Coaching bei der Verwendung der Benutzerschnittstellen (Frontends) zum Aufbau des Berichtswesens
* laufende Betreuung
* Durchführung von Schulungen und Trainings zur praktischen Arbeit mit den OLAP-Datenbanken
* Migration Microsoft SQL Server 2000 auf Microsoft SQL Server 2005

Datenquellen:

* SAP
* Excel
* Textdateien
* Access
* ...

Anforderungsanalyse, Konzeption, Kommunikation mit Fachbereich, Entwicklung, Dokumentation, Test, Performance Optimierung, Wartung, Beratung, Berichtswesen

* Microsoft SQL Server 2000 (relational, MSAS, DTS) (on-premise)
* Microsoft SQL Server 2005 (relational, SSAS, SSIS) (on-premise)
* Bissantz Deltamaster
* Softpro CubePlayer
* MIS Plain
* MIS Onvision
* MIS Integration Framework
* Subversion

Referenzen:
* xref:goertz-references.adoc#referenz_vivantes_1[]
* xref:goertz-references.adoc#referenz_vivantes_2[]


== 10/2008 - 12/2009; Rudolf Wöhrl AG

Branche:: Konsumgüter und Handel

Größe:: 1000-5000 Mitarbeiter

=== BI-Team (Controlling, Finanzen, IT), Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

Projektinhalte:

* Personalcontrolling
* Personaleinsatzplanung
* Migration Microsoft SQL Server 2000, 2005 auf Microsoft SQL Server 2008 (on-premise)
* Berichtswesen mit Bissantz Deltamaster
* Subversion (?)

Datenquellen:

* diverse

[#project_rentenbank_2009]
== 09/2005 - 01/2009; Landwirtschaftliche Rentenbank

Branche:: Banken und Finanzdienstleistungen

Größe:: 50-250 Mitarbeiter

=== IT-Anwendungsentwicklung, Bereich "Datawarehouse und OLAP", Microsoft BI-Analyse-Plattform: Microsoft BI Architekt und Entwickler

Projektinhalte:

* Konzeption 
** Produktionseinsatzverfahren (Workflow, Verwendung von Subversion)
** Entwicklungsstandards
** Testkonzepten
* Weiterentwicklung des Datawarehouse und der OLAP-Anwendungen
* Migration Microsoft SQL Server 2000 auf Microsoft SQL Server 2005
* Situations- und Bedarfsanalyse der Anforderungen von Fachanwendern
* Erarbeitung fachlicher und technischer Konzepte zur Umsetzung
* Konzeption und Durchführung von Schulungen zur praktischen Arbeit mit den OLAP-Datenbanken
* fachliche Schwerpunkte:
* IAS- und HGB-Bilanzen
* Controlling
* Geldhandel und Emissionsgeschäft (Wertpapiere)

Datenquellen:

* iSeries (AS 400)

Anforderungsanalyse, Konzeption, Kommunikation mit Fachbereich, Entwicklung, Dokumentation, Test, Performance Optimierung, Wartung, Beratung, Berichtswesen

* Microsoft SQL Server 2000 (relational, MSAS, DTS) (on-premise)
* Microsoft SQL Server 2005 (relational, SSAS, SSIS, SSRS) (on-premise)
* MIS Plain
* Datawarehouse Explorer
* Subversion

Referenz: xref:goertz-references.adoc#referenz_rentenbank[]

== 09/2004 - 10/2004; ID GmbH

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 10-50 Mitarbeiter

=== Entwicklung eines analytischen Zusatzmoduls für einen DRG-Grouper, inklusive Szenarien und Kostenmodul: Microsoft BI Architekt und Entwickler

Datenquellen:

* §21 Daten
* IMC Daten oder andere Formate
* obige Quellen Input für DRG-Grouper
* zusätzlich optional fallbezogene Kosten-Daten

* Microsoft SQL Server 2000 (relational, DTS, MSAS) (on-premise)
* Excel
* Cubeware Analysesystem

[#project_infor_2004]
== 09/1999 - 09/2004; MIS GmbH

Brache:: Beratung

Größe:: 500-1000 Mitarbeiter

=== angestellter BI Architekt und Entwickler

Projektinhalte:

Kunden- und Projektakquisition

* Führen von Erstkontaktgesprächen
* Präsentation des MIS Leistungsangebotes
* Betreuung von Interessenten auf Akquisitionsveranstaltungen mit dem Ziel der Neukundengewinnung
* Durchführung von Akquisitionsworkshops
* Angebotserstellung
* Situationsanalyse beim Kunden
* Erfassen der betriebswirtschaftlichen u. technischen Kundenanforderungen an DV-Systeme
* Erarbeitung von betriebswirtschaftlichen u. technischen Konzepten gemeinsam mit dem Kunden
* Durchführung von Konzeptionsworkshops

Implementierung von Analyse- und Reportingsystemen

* Übernahme von Projektverantwortung
* Realisierung von Aufgabenlösungen unter Zuhilfenahme gängiger Datenbank-Technologien und Programmiersprachen
* Abstimmung der Aufgabenlösung im Hinblick auf die Gesamtlösung gegenüber dem Projektteam
* Abstimmung der Aufgabenlösung in Hinsicht auf das betriebswirtschaftliche Konzept mit den Kunden
* Konzeption und Durchführung von individuellen Kundenschulungen

mehrfache Migrationen von MIS Alea auf MSAS 2000 (Microsoft Analysis Services)

Referenz: xref:goertz-references.adoc#referenz_infor[]

=== folgende Projekte wurden als Berater für Business Intelligence bei Kunden der MIS durchgeführt. Bei den namentlich genannten Firmen handelt es sich um Referenzkunden der MIS GmbH (jetzt infor)

=== 01/2004 - 05/2004 Konzeption und Umsetzung der "*21-DRG-Analyse" (für Krankenhäuser)

Datenquellen:

* 21 Daten, IMC Daten; Bewertungsdaten von DRG-Groupern; zusätzlich optional fallbezogene Kosten-Leistungsdaten

Datawarehouse: Microsoft SQL Server (on-premise)

ETL: TSQL, DTS

OLAP-Datenbanken: Microsoft Analysis Services (MSAS), MIS Alea

=== 05/2001 - 05/2004; Medienhaus Aschendorff (über MIS GmbH)

Branche:: Medien und Verlage

Größe:: 500-1000 Mitarbeiter

==== Konzeption und Implementierung eines Anzeigeninformationssystems (AIS): angestellter BI Architekt und Entwickler

Konzeption und Implementierung eines Anzeigeninformationssystems (AIS)

Konzeption, Modellierung und Betreuung der analytischen Datenbank und der dazugehörigen ETL-Prozesse. Erweiterung des bestehenden Datawarehouse.

Betreuung und Schulung bei der Verwendung von MIS Plain zur Erstellung des Berichtswesens.

Datenquellen: VI&VA, eine SAP basierte operative Erweiterung für Zeitungsverlage, einige andere Datenquellen

Datawarehouse: Microsoft SQL Server, konkret wurde "VIVAinfo" (ein spezielles Datawarehouse basierend auf VI&VA), um Objekte und ETL-Prozesse erweitert, so dass die analytische Datenbank gefüllt werden kann.

ETL: TSQL und DTS

Analytische Datenbank: Microsoft Analysis Services (MSAS)

=== 01/2004 - 05/2004; MIS GmbH

Branche:: Beratung

Größe:: 250-500 Mitarbeiter

==== Konzeption und Umsetzung der "§21-DRG-Analyse" (für Krankenhäuser)

Branche:: Gesundheitswesen, Krankenhaus

Datenquellen: §21 Daten, IMC Daten; Bewertungsdaten von DRG-Groupern; zusätzlich optional fallbezogene Kosten- Leistungsdaten

Datawarehouse: Microsoft SQL Server

ETL: TSQL, DTS

OLAP-Datenbanken: Microsoft Analysis Services (MSAS), MIS Alea

Benutzerschnittstellen (Frontends): MIS Onvision, MIS Plain

=== 01/2004 - 04/2004; VzE - Verein zur Errichtung evangelischer Krankenhäuser

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 5000-10.000 Mitarbeiter

==== Medizincontrolling, DRG-Controlling und -Berichtswesen Konzeption, Modellierung und Betreuung der relationalen und analytischen Datenbanken und der dazugehörigen ETL-Prozesse

Coaching bei der Verwendung verschiedener Benutzerschnittstellen (Frontends) (MIS Plain, MIS Onvision) zur Erstellung des Berichtswesens.

Durchführung von Schulungen zur Benutzung der Software und zur Arbeit mit den Datenbanken.

Datenquellen: diverse: *21 Daten, manuelle Quellen, SAP, ...

Datawarehouse: Microsoft SQL Server

ETL: TSQL, DTS

OLAP-Datenbanken: Microsoft Analysis Services (MSAS)

Benutzerschnittstellen (Frontends): MIS Onvision, MIS Plain

=== 09/2001 - 12/2003; KCC (über MIS GmbH)

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 10-50 Mitarbeiter

==== (Branche Krankenhäuser) Konzeption, Entwicklung und Betreuung der "DRC" (Diagnosis Related Costs) für verschiedene Darstellungen der Kostenträgerrechnung. Gemeinsam mit einem Partner der MIS

So wie es sich bei den DRG's um Erlöse handelt, ermöglichen die DRC's eine strukturidentische Gegenkalkulation der Kosten.

Deckungsbeitragsberechnungen.

Die DRC's wurden in verschiedenen Krankenhäusern eingesetzt.

Datenquellen: je nach Krankenhaus unterschiedliche Quellen

Datawarehouse: Microsoft SQL Server

ETL: TSQL, DTS, MS Access, MS Excel

OLAP-Datenbanken: Microsoft Analysis Services (MSAS)

Benutzerschnittstellen (Frontends): MIS Onvision, MIS Plain

=== 09/2000 - 03/2002; Märkische Oderzeitung (über MIS GmbH)

Branche:: Medien und Verlage

==== Anzeigeninformationssystem (AIS), basierend auf Daten aus VI&VA

Datenquellen: SAP, VI&VA.

ETL: Access, Excel

analytische Datenbank: MIS Alea

Frontend: MIS Alea Excel Integration

=== 01/2001 - 12/2001; MIS GmbH

Branche:: Gesundheitswesen, Krankenhaus

Größe:: 250-500 Mitarbeiter

==== Konzeption und Umsetzung der "MIS Business Solution Krankenhäuser"

Datawarehouse: Microsoft SQL Server

ETL: TSQL, DTS

analytische Datenbanken: MIS Alea, Microsoft Analysis Services (MSAS)

=== 12/1999 - 09/2000; Deutsche Telekom (über MIS GmbH)

Branche:: Telekommunikation

Größe:: >10.000 Mitarbeiter

==== Umstellung einer analytischen Anwendung von MIS Alea auf MS Analysis Services (bzw. damals noch MS OLAP Services) unter Beibehaltung des bestehenden Berichtswesens und andere Anpassungen

technische Projektleitung

Datawarehouse: Microsoft SQL Server

ETL: TSQL, DTS

analytische Datenbanken: MIS Alea, Microsoft OLAP Services

Frontend: MIS Alea Excel Integration

=== 09/1999 - 05/2004 diverse Projekte / diverse Branchen (u. a. Energiewirtschaft, Versicherungen, Banken, ...)
