= Impressum
:page-subtitle:
//für kompatibilität mit beworbenen Links:
// :toc: auto
// :toclevels: 2
// :sectnums:
// include::_footnotes.adoc[]
include::_localization.adoc[]
include::_footnotes.adoc[]
:imagesdir: /assets/img

ifndef::env-site[]

//it's not executed on gitlab server in jekyll
//locally (VCS, export to docx) we need a different :imagesdir:
:imagesdir: ./assets/img

// auf dem Server wird der :page-subtitle: unter dem Titel angezeigt
// local nicht, also blenden wir ihn ein
// docbook könnte mit spezieller Syntax auch einen subtitle anzeigen, das geht aber nicht mit html5
// https://docs.asciidoctor.org/asciidoc/latest/document/subtitle/

[discrete] 
=== {page-subtitle}

endif::env-site[]


Germo Görtz +
// IT Beratung für Analytische Informationssysteme und Berichtssysteme
Selbitzer Str. 118 +
14089 Berlin


== Kontakt

VoIP (Satellite): +49 15678 682219 +
E-Mail: web[@]germo-goertz.de

== Umsatzsteuer-ID

Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: +
DE221722008

== Redaktionell verantwortlich

Germo Görtz +
// IT Beratung für Analytische Informationssysteme und Berichtssysteme
Selbitzer Str. 118 +
14089 Berlin

== Verbraucherstreitbeilegung/Universalschlichtungsstelle

Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer
Verbraucherschlichtungsstelle teilzunehmen.

== Haftung für Links

Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.

Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.

== Urheberrecht

Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.

Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.



Quelle:
https://www.e-recht24.de
