= Sample Adoc Page
Germo Görtz
2022-02-20 10:30:00
:page-category: Test
:page-permalink: /sample-adoc/
:url-asciidoctor: http://asciidoctor.org
//:page-title: Das ist der Titel
:page-subtitle: und das ist der Untertitel
:page-tags: [tag1, tag-2, tag 3]
:page-last-updated: 2022-02-16
// folgendes kann genutzt werden, um den Wert aus dem Dateinamen zu überschreiben
//:revdate: 2022-02-20 10:30:00 +0200
:head-extra: head_extra.html
:toc: auto
// :page-layout: info
:page-layout: post


Wenn ein title definiert wurde, dann wird der statt des Header 1 angezeigt. Wenn kein title definiert wurde, wird der Header 1 verwendet.

subtitle erscheint auch im jekyll. Man muss die richtigen Attribute korrekt definieren. Insbesondere mit prefix "page-"

subtitle erscheint aber nicht im gerenderten AciiDoc, also auch nicht im docx. Da muss man noch eine Lösung finden.

== Header 2

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {url-asciidoctor}[Asciidoctor].

Siehe auch: https://github.com/asciidoctor/jekyll-asciidoc[]

=== Header 3

Noch etwas Inhalt

* Listenzeile 1
* Listenzeile 2
** Zeile 2.2

[source,ruby]
puts "Hello, World!"