= Sample Adoc Page
Germo Görtz
2022-02-20 10:30:00
:page-category: Test
:page-permalink: /sample-adoc/
:url-asciidoctor: http://asciidoctor.org
//:page-title: Das ist der Titel
:page-subtitle: und das ist der Untertitel
:page-tags: [tag1, tag-2, tag 3]
:page-last-updated: 2022-02-16
// folgendes kann genutzt werden, um den Wert aus dem Dateinamen zu überschreiben
//:revdate: 2022-02-20 10:30:00 +0200
:head-extra: head_extra.html
:toc: auto
// :page-layout: info
:page-layout: post


Wenn ein title definiert wurde, dann wird der statt des Header 1 angezeigt. Wenn kein title definiert wurde, wird der Header 1 verwendet.


env-site: 
{env-site}

env: 
{env}

site-gen:
{site-gen} 

subtitle erscheint auch im jekyll. Man muss die richtigen Attribute korrekt definieren. Insbesondere mit prefix "page-"

subtitle erscheint aber nicht im gerenderten AciiDoc, also auch nicht im docx. Da muss man noch eine Lösung finden.

== Header 2

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {url-asciidoctor}[Asciidoctor].

Siehe auch: https://github.com/asciidoctor/jekyll-asciidoc[]

Asciidoctor

In addition to the built-in attributes in AsciiDoc, the following additional AsciiDoc attributes are automatically defined by this plugin and available to all AsciiDoc-based pages:

----
site-root=(absolute path of root directory)
site-source=(absolute path of source directory)
site-destination=(absolute path of output directory)
site-baseurl=(value of the baseurl config option)
site-url=(value of the url config option)
env=site
env-site
site-gen=jekyll
site-gen-jekyll
builder=jekyll
builder-jekyll
jekyll-version=(value of the Jekyll::VERSION constant)
idprefix
idseparator=-
linkattrs=@
----

The following additional attributes are defined per page:

  outpath=(path of page relative to baseurl


You can pass custom attributes to AsciiDoc, or override default attributes provided by the plugin, using the attributes option of the asciidoctor block in your _config.yml. The value of this option can either be an Array containing key-value pairs:



Asciidoctor Diagram is a set of extensions for Asciidoctor that allow you to embed diagrams generated by PlantUML, Graphviz, ditaa, Shaape, and other plain-text diagram tools inside your AsciiDoc documents. In order to use Asciidoctor Diagram in a Jekyll project successfully, you must use a version of this plugin >= 2.0.0. Other combinations are known to have issues.



=== Header 3

Noch etwas Inhalt

* Listenzeile 1
* Listenzeile 2
** Zeile 2.2

[source,ruby]
puts "Hello, World!"