// tag::message01[]

== Über mich

:fn-blog-kh-autobauer: footnote:kh-autobauer[Hintergründe zu "Technokratie statt Demokratie" im "Gleichnis vom Krankenhaus der Autobauer" https://blog.germo-goertz.de/2022-09-15-krankenhaus-autobauer/[]]

Mein Name ist Germo Görtz. Und ich bin darauf spezialisiert, analytische Informations-Systeme und Berichts-Systeme technisch zu konzipieren und zu implementieren, damit sie **fachlich funktionieren**.

Meine Kunden erwarten von mir keine strategische Beratung, denn sie sind Profis, kennen ihr Fach und ihre Ziele. +
Ich bin der Weihnachtsmann des kompetenten Controllers. +
Je kniffliger die Aufgabe, desto größer mein Mehrwert.

Ihr Kittel brennt? Ich bin Ihr Feuerlöscher!

image::kybernetik06.svg[]

Sie wissen, wo Sie hinwollen. Ich analysiere und verstehe Ihre Ziele, dann werde ich Ihr Pfadfinder und führe oder fahre oder fliege Sie zu Ihren Zielen.



Meine _technische und konzeptionelle_ Erfahrung ergänzt Ihre _fachliche_ Erfahrung +
=> für Ihre Karriere und Ihren Erfolg!

Folgende Faktoren machen unser gemeinsames Projekt besonders fruchtbar:

* Exzellenz durch Kompetenz
* Handwerk statt Fließband
* Vertrauen in Experten (Technokratie statt Demokratie{fn-blog-kh-autobauer})

Für die Umsetzung nutze ich primär meine in Jahrzehnten erworbenen Kenntnisse und Erfahrungen mit der *Microsoft BI Plattform*: SQL Server, Power BI, relationale und analytische Datenbanken, maschinelles Lernen. Meine besondere Stärke ist die Erstellung von Datenmodellen.

Vergütung:

* Besonders motivierend ist eine Zusammenarbeit, bei der ich Expertise und Zeit investieren kann, um am messbaren Erfolg beteiligt zu werden.
* Gewerke und Festpreise sind möglich.
* Ansonsten tausche ich Zeit gegen Geld und werde nach Stunden bezahlt.


Am Ende meines IT-Profils finden Sie link:https://blog.germo-goertz.de/goertz_profile_de/#referenzen[*Referenzen zufriedener Kunden*].

// end::message01[]


Lernen Sie mich kennen, bewerben Sie sich mit Ihren Ideen und Projekten, investieren Sie in die Zusammenarbeit mit mir: +
=> für Ihren Erfolg! +
Schreiben Sie mir, rufen Sie mich an, buchen Sie einen Termin!


// // tag::message[]

// * Mein Name ist *Germo Görtz*. +
// Und ich bin darauf spezialisiert, *Baufinanzierungs-Wünsche* meiner Kunden *zu unschlagbaren Konditionen* an Banken zu vermitteln.
// * Unser Team betreut seit über 30 Jahren mehrere Tausend zufriedene Kunden, +
// unter anderem auch mich und *meine eigenen Immobilien-Investitionen*.
// * Als begeisterter Kunde bin ich inzwischen selbst Teil dieses Teams geworden, um auch andere Immobilien-Investoren beim Vermögensaufbau zu unterstützen.
// * Meine *Investitions-Erfahrung* und unsere *Baufinanzierungs-Expertise* +
// => für *Ihre erfolgreiche Immobilien-Investition*! +
// https://www.dvag.de/germo.goertz[Agentur Germo Görtz]


// TIP: Mein kostenloser online-Kurs https://akademie.germo-goertz.de/customer-new/free-course/double?course_id=THURE752WAFH["Grundlagen der Baufinanzierung: Konzepte, Wissen, Expertentipps"]

// {empty} +

// image::kybernetik-baufi.svg[]

// {empty} +

// TIP: Kostenlose Immobilien-Investitions-Analysen für meine Baufinanzierungs-Kunden!

// {empty} +

// video::U1MpMj04bg0[youtube,960,540]

// //https://youtu.be/U1MpMj04bg0


// // end::message[]

=== Schreiben Sie mir eine Nachricht

// Formular
// https://www.staticforms.xyz/
++++
<div class="container">
  <div class="columns">
    <!-- Make sure you don't change the form action-->
    <form action="https://api.staticforms.xyz/submit" method="post">
        <!-- Replace with accesKey sent to your email -->
        <input type="hidden" name="accessKey" value="fb830ca8-ccfe-47a9-8b08-dfe418125ad6"> <!-- Required -->
        <input type="hidden" name="subject" value="Web-Formular blog.germo-goertz"> <!-- Optional -->
        <div class="field">
          <label class="label">Name:*</label>
          <div class="control">
            <input class="input" type="text" name="name" placeholder="Ihr Name" required>
          </div>
        </div>
        <div class="field">
          <label class="label">E-Mail:*</label>
          <div class="control">
            <input class="input" type="email" name="email" placeholder="Ihre E-Mail" required>
          </div>
        </div>
        <div class="field">
          <label class="label">Telefon:</label>
          <div class="control">
            <input class="input" name="phone" placeholder="+49 123 4567890 (optional)">
          </div>
        </div>
        <div class="field">
          <label class="label">Nachricht:*</label>
          <div class="control">
            <textarea class="textarea" name="message" placeholder="Ihre Nachricht (Zeilenumbrüche werden entfernt)" required></textarea>
          </div>
        </div>
        <!-- Specify @ as reply to value if you want it to be customers email -->
        <input type="hidden" name="replyTo" value="@"> <!-- Optional -->
        <input type="submit" value="Abschicken" />
        <!-- If we receive data in this field submission will be ignored -->
        <input type="text" name="honeypot" style="display: none;"> <!-- Optional -->
        <!-- If you want form to redirect to a specific url after submission -->
        <input type="hidden" name="redirectTo" value="https://blog.germo-goertz.de/nachricht-verschickt/"> <!-- Optional -->
    </form>
  </div>
</div>
++++

....
* Diese Felder müssen ausgefüllt werden.
....
